---
- name: Resolve package name
  set_fact:
    package_name: "\
      {{ (item.value.package_name is defined and item.value.package_name | length > 0) |\
      ternary(item.value.package_name, item.value.name) }}"

- name: Get {{ item.key }} latest version
  block:
    - name: Get latest version
      uri:
        url: "{{ item.value.version_lookup_url }}"
        return_content: yes
        status_code: 200
      register: version_lookup_response

    - name: Process latest version
      set_fact:
        latest_version: >-
          {{ lookup('vars', '{{ item.key }}_response_processor') }}
  when: item.value.version | lower == 'latest'

- name: Form {{ item.key }} version
  block:
    - name: Resolve version
      set_fact:
        resolved_version: >-
          {{ (item.value.version | lower == 'latest') | ternary(latest_version, item.value.version) }}

    - name: Show resolved version
      debug:
        msg: "Version of {{ item.key }} to install: {{ resolved_version }}"

- name: Determine if {{ item.key }} already installed
  stat:
    path: >-
      {{ item.value.install_dir }}/{{ package_name }}
  register: package_installed

- name: Determine current package version
  block:
    - name: Get latest package version
      # noqa 305
      shell: >-
        {{ item.value.install_dir }}/{{ item.value.package_path }}/{{ item.value.version_extractor }}
      register: current_package_version
      changed_when: False
      failed_when: False

    - name: Show currently installed version
      debug:
        msg: >-
          Currently installed package version: {{ current_package_version.stdout }}
  when: package_installed.stat.exists

- name: Install {{ item.key }} package
  block:
    - name: Create temporary download directory
      tempfile:
        state: directory
        suffix: "{{ item.key }}"
      register: download_directory

    - name: Download {{ item.key }} package
      get_url:
        url: "{{ lookup('vars', '{{ item.key }}_package_url') }}"
        dest: "{{ download_directory.path }}"
      register: download_path

    - name: Unzip {{ item.key }} package to destination directory
      become: true
      unarchive:
        src: "{{ download_path.dest }}"
        dest: "{{ item.value.install_dir }}"
        copy: no
        owner: root
        group: root
        mode: 0755
      when: item.value.unarchive | bool

    - name: Copy {{ item.key }} package to destination directory
      become: true
      copy:
        src: "{{ download_path.dest }}"
        dest: >-
          {{ item.value.install_dir }}/{{ package_name }}
        owner: root
        group: root
        mode: 0755
        remote_src: yes
      when: not item.value.unarchive | bool
  when: "not package_installed.stat.exists or \
    resolved_version.find(current_package_version.stdout) == -1"

- name: Configure {{ package_name }} dotfile
  block:
  - name: Create dotfile
    template:
      src: "{{ item.value.dotfile }}.j2"
      dest: "{{ ansible_env.HOME }}/.{{ item.value.dotfile }}"
      mode: 0644

  - name: Configure dotfile in .bashrc
    blockinfile:
      dest: "{{ bashrc_path }}"
      marker: "# {mark} ANSIBLE MANAGED BLOCK: {{ package_name }}"
      block: |
        if [ -f "$HOME/.{{ item.value.dotfile }}" ]; then
          source "$HOME/.{{ item.value.dotfile }}"
        fi
  when: item.value.dotfile is defined and item.value.dotfile | length > 0
