---
- name: Converge
  hosts: all

  pre_tasks:
    - name: "Update apt cache"
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family | lower == 'debian'

  tasks:
    - name: "Include ansible-role-golang"
      include_role:
        name: "ansible-role-golang"
      vars:
        golang_version: "1.13.8"
